apiVersion: v1
kind: Pod
metadata:
  labels:
    pod-mutating-webhook-enabled: "true"
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
