apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-mutating-webhook
webhooks:
  - name: pod-webhook-mutator.kb.io
    clientConfig:
      service:
        name: pod-webhook-mutator
        namespace: default
        path: /mutate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ0RENDQXNpZ0F3SUJBZ0lVR3FFTEZTTnRLZkgyM0hyZmV6bWV1Ti80WUI4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZTM1ZpWlhKdVpYUmxjeUJCWkcxcGMzTnBiMjRnUTI5dWRISnZiR3hsY2pBZQpGdzB5TlRBek1ESXdPVE13TURoYUZ3MHlOakF6TURJd09UTXdNRGhhTUI0eEhEQWFCZ05WQkFNTUUzQnZaQzEzClpXSm9iMjlyTFcxMWRHRjBiM0l3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRDgKeGtjMWhNbVdCTUd4Z04zbzhVNFU2YmorVVcwZk5mSHBsTjNyQ1graDJIaVhJTzljK09oK3pvTUVleTNKMjJLNQpEWFh1eHpaWCtYTFoxWjA1UnRNS1NuVlhKdmdyUGx3a1M3cnAxeUtMaEtvYnE2dURTTzcwRWNsaVhXblNJOTJOCkRnQXhOczRWQzVGRjBUdVFpVG54TnFNZzg4QkIyZGoxUkE4UThpTGlBOHM0NUtveVMvcVovbVBYT1paY0trSnYKTVJyMkZjVGJqd2d6cjlFRXNLeUVVVi9UWG1kRXFQalJHWmtydllTRW91V3dLcmJaNk5CZFh5eSswYW9rMXRlKwpVWGJqOXlEVyswM09vV1J0N2h6dGdqR3huaXpabFNEcDd0TU1BdlNXZWpjTm1zSlZ2NGZBWWlnN1BXUVVSZk9pCjc2NHJ1ZjFUNTNnaTdWZjNxS1pUQWdNQkFBR2pnZ0VJTUlJQkJEQ0J3UVlEVlIwUkJJRzVNSUcyZ2kxd2IyUXQKZDJWaWFHOXZheTF0ZFhSaGRHOXlMbVJsWm1GMWJIUXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXeUNKM0J2WkMxMwpaV0pvYjI5ckxXMTFkR0YwYjNJdVpHVm1ZWFZzZEM1emRtTXVZMngxYzNSbGNvSWZjRzlrTFhkbFltaHZiMnN0CmJYVjBZWFJ2Y2k1a1pXWmhkV3gwTG5OMlk0SWJjRzlrTFhkbFltaHZiMnN0YlhWMFlYUnZjaTVrWldaaGRXeDAKZ2hOd2IyUXRkMlZpYUc5dmF5MXRkWFJoZEc5eWdnbHNiMk5oYkdodmMzUXdIUVlEVlIwT0JCWUVGSXFlUFFDTgpBeWpTMUFNN1lXeFUrN3A2Q3Y1WU1COEdBMVVkSXdRWU1CYUFGT2JJRy9TaGJuREtIeTE2L0RuU1NxdWdETWFDCk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWtQVTJpRDQ5b1l5bkt0MVhvK09OTStIRFBreGdCaHl3Yk8vdWkKZ0l1d2lqb0tJOUhkNmJmZ1pIN01FOHVIK0VqWGIxMmQ1YWFhcnF5SkZRUGtPS3FGRE1ZN29lVmQrWCtQWmJlRAp2WHdaTjZ1MHZyNGhDaVhjMXVvY0pJdmhLaFh1WXJ3eEhKUlRjTk15RkM2QTU2dUFON3B3eE9CamlvRVJmZVBLCkVhOUhvSVZQd2w0ZGZ4NmVTRDhyVGN1b2p6aEZicVk1b21Mb041TUE2N3VkNDU1WUxJbHRrYjlKTjJUL3p0ZGoKZGY3T01DbkFMMkh1aDROVDFRTkY0ckNTdkVjMjlyVUNYYk9nSDI2T09iWUl3QnNUZVRTYzhjc293TlhkK3pKTApLWTRJdTYxOVlEdXQ5Wm8wRUoxaXNOemJtcWU4UTl3clIzb1JiV05YZDlFMkNyNHUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 30
    objectSelector: # Very important to restrict the webhook to mutate the only pods with the label
      matchLabels:
        pod-mutating-webhook-enabled: "true"
